
os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: true

after_build:
- cmd: >-
    CD %APPVEYOR_BUILD_FOLDER%\dist\
    appveyor PushArtifact h2decompress.exe

test_script:
  - cargo test --verbose %cargoflags%
