[package]
name = "h2decompress"
version = "0.1.0"
authors = ["Camden Smallwood <camden.smallwood@gmail.com>"]
edition = "2018"

[dependencies]
deflate = { git = "https://github.com/camden-smallwood/deflate-rs.git", branch = "dev" }
inflate = "*"
